repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: 5685ac183889dcafd0ea6c9dc3df211274554ec2  # frozen: v0.2.2
    hooks:
      - id: yamlfmt
      - id: poetry-check-lock
      - id: find-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: e1668fe86af3810fbca72b8653fe478e66a0afdc  # frozen: v3.2.0
    hooks:
      - id: check-merge-conflict
        exclude: \.rst$

      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first

      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: \.vbs$

      - id: mixed-line-ending
        args: [--fix=crlf]
        files: \.vbs$

      - id: check-json
      - id: check-added-large-files  # check for file bigger than 500kb
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/asottile/pyupgrade
    rev: f766c29ec4bb6cf2674b81959871e59d5400380a  # frozen: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260  # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/timothycrosley/isort
    rev: 2e02c195afdb499be9068ca0d08c9d7d45912d4d  # frozen: 5.5.4
    hooks:
      - id: isort
        args:
          - --line-width=88
          - --trailing-comma
          - --length-sort
          - --multi-line=3
          - --project=bgmi
          - --force-grid-wrap=0
          - --use-parentheses
          - -sd=THIRDPARTY

  - repo: https://github.com/psf/black
    rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
    hooks:
      - id: black
